### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by EhsanVahab** [JohannesBuchner/spoken-command-recognition#1]
Dear @JohannesBuchner ,
I really appreciate you for your great solution to simplify the problem of voice recognition.
I know such a dataset you've provided is invaluable but I'm just wondering would it be possible to share your great dataset only for academical use?

**Comment by JohannesBuchner** [comment]
I am not sure I understand your question. The data set and code are free to use. For academic use, a citation is appreciated, see https://www.kaggle.com/jbuchner/synthetic-speech-commands-dataset/home and https://www.kaggle.com/jbuchner/spokenverbs/home

**Comment by EhsanVahab** [comment]
When I posted this issue I had not paid enough attention to how you provided the dataset.
I created it and test it by NN.
It's great and I deeply appreciate you

**Comment by JohannesBuchner** [comment]
Thanks, I hope it is useful.
